name: Fetch Keywords and Save Results

on:
  workflow_dispatch:
    inputs:
      query:
        description: "Query for the keyword search"
        required: true
        default: "mood tracker"
      rankingDifficultyStart:
        description: "Start value for rankingDifficulty"
        required: true
        default: 1
      rankingDifficultyEnd:
        description: "End value for rankingDifficulty"
        required: true
        default: 100
      searchVolumeMin:
        description: "Minimum search volume"
        required: true
        default: 500

jobs:
  fetch-and-commit-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensures we can push changes back to the repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      - name: Run the script
        env:
          QUERY: ${{ github.event.inputs.query }}
          RANKING_DIFFICULTY_START: ${{ github.event.inputs.rankingDifficultyStart }}
          RANKING_DIFFICULTY_END: ${{ github.event.inputs.rankingDifficultyEnd }}
          SEARCH_VOLUME_MIN: ${{ github.event.inputs.searchVolumeMin }}
        run: |
          python3 main.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Results
        run: |
          git add keywords_results.csv
          git commit -m "Add keywords results from query '${{ github.event.inputs.query }}'"
          git push origin HEAD
