name: Keyword Analysis Automation

on:
  workflow_dispatch:
    inputs:
      queries:
        description: "Comma-separated list of keywords (e.g., mood tracker, wellness app)"
        required: false
      rankingDifficultyStart:
        description: "Start value for ranking difficulty (default: 1)"
        required: false
        default: 0
      rankingDifficultyEnd:
        description: "End value for ranking difficulty (default: 100)"
        required: false
        default: 100
      searchVolumeMin:
        description: "Minimum search volume (default: 500)"
        required: false
        default: 0
      searchVolumeMax:
        description: "Maximum search volume (default: None)"
        required: false
        default: None
      filename:  # New input for filename
        description: "Filename to save the results (default: keywords_results.csv)"
        required: false
        default: "keywords_results.csv"

jobs:
  keyword-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx

      - name: Run Keyword Analysis Script
        env:
          QUERIES: ${{ inputs.queries }}
          RANKING_DIFFICULTY_START: ${{ inputs.rankingDifficultyStart }}
          RANKING_DIFFICULTY_END: ${{ inputs.rankingDifficultyEnd }}
          SEARCH_VOLUME_MIN: ${{ inputs.searchVolumeMin }}
          SEARCH_VOLUME_MAX: ${{ inputs.searchVolumeMax }}
          FILENAME: ${{ inputs.filename}}
        run: |
          python main.py
      # Step 5: Commit results to repository
      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Add keyword analysis results"
          git push
